version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/ailienant-core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ailienant-extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
