# ailienant-core/brain/state.py

import inspect
import logging
import operator
import os
from typing import Any, Callable, TypedDict, List, Dict, Optional, Annotated, Literal
from pydantic import BaseModel, Field, model_validator

from shared.hardware import HardwareProfile  # noqa: E402 — imported for type annotation

# =====================================================================
# 1. DATA MODELS (strict runtime validation contracts)
# =====================================================================
# Pydantic enforces the fail-fast principle here. If the LLM (Planner)
# hallucinates the JSON structure, the system fails and retries immediately
# rather than propagating corrupt data to the Orchestrator or the CoderAgent.


# Phase 4.1.4 — Legacy → new role-name migration (blueprint §3.1).
# Maps the deprecated 5-value vocabulary onto the canonical 8-value vocabulary.
# Consumed by WBSStep.__migrate_legacy_target_role__ as a before-validator so
# every stored target_role is always one of the 8 NEW canonical names. The legacy
# 5 values + this map will be removed one release after Phase 4 closes (logged
# in PROJECT_MANIFEST.md Tech Debt section).
_LEGACY_TO_NEW_ROLE: Dict[str, str] = {
    "Refactor": "architect_refactor",
    "Infra": "devops_infra",
    "Doc": "doc_manager",
    "SecOps": "secops",
    "Test": "qa_tester",
}

# Phase 7.12 — canonical post-migration role vocabulary. An out-of-vocabulary
# target_role string hallucinated by the Planner is coerced to this default rather
# than raising a ValidationError (which would burn a planner retry).
_CANONICAL_ROLES: frozenset[str] = frozenset({
    "core_dev", "architect_refactor", "devops_infra", "secops",
    "qa_tester", "doc_manager", "vcs_manager", "data_ml_engineer",
})
_DEFAULT_ROLE = "core_dev"


def _coerce_to_str(item: Any) -> str:
    """Phase 7.12 — flatten a hallucinated list element into a plain string.

    The Planner LLM intermittently emits objects (``{"file": "x", "reason": "y"}``)
    where the MissionSpecification contract requires a ``str``. Rather than fail
    validation, flatten: dicts become ``"key: value"`` pairs; everything else is
    stringified. Already-strings pass through untouched.
    """
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        return "; ".join(f"{k}: {v}" for k, v in item.items())
    return str(item)


def _coerce_str_list(value: Any) -> Any:
    """Phase 7.12 — normalise a value destined for a ``List[str]`` field.

    Maps each element through :func:`_coerce_to_str`. A bare scalar/dict (LLM
    emitted a single value instead of a list) is wrapped into a one-element list.
    Non-coercible input is returned unchanged so Pydantic still fails loudly.
    """
    if isinstance(value, list):
        return [_coerce_to_str(el) for el in value]
    if isinstance(value, (str, dict)):
        return [_coerce_to_str(value)]
    return value


class WBSStep(BaseModel):
    """A single, atomic, executable step within a MissionSpecification.

    The target_role Literal accepts both legacy (5) and new (8) canonical values.
    A model_validator(mode="before") normalises legacy strings to canonical names
    at construction, so the stored value is always one of the 8 canonical names.
    """

    step_number: int = Field(
        description="Sequential execution order (1, 2, 3...)."
    )
    target_role: Literal[
        # Legacy 5 (deprecated, auto-migrated to the new vocabulary):
        "Refactor", "Infra", "Doc", "SecOps", "Test",
        # New 8 (canonical Phase 4 vocabulary):
        "core_dev", "architect_refactor", "devops_infra", "secops",
        "qa_tester", "doc_manager", "vcs_manager", "data_ml_engineer",
    ] = Field(
        default="core_dev",
        description="The RBAC role the CoderAgent assumes for this step (Phase 4.1.4).",
    )
    action: Literal["read_file", "write_file", "edit_file", "run_command"] = Field(
        description="Strict action type for this step."
    )
    target_file: str = Field(
        description="Exact path of the affected file (e.g. 'src/routes/auth.py') or command to run."
    )
    description: str = Field(
        description="Detailed instruction for the CoderAgent to execute at this step."
    )
    status: Literal[
        "pending", "in_progress", "completed", "failed",
        # 13.0.9 — incremental per-step approval widens the lifecycle: a step
        # generated by the coder now pauses for a human decision before it is
        # honestly "completed". awaiting_approval = generated, pending a
        # human decision; rejected = terminal, the human declined it outright
        # (distinct from failed, which is a system-side fault); revision_requested =
        # non-terminal, the human asked for a different attempt with feedback,
        # re-dispatched to the coder (bounded by APPLY_REJECT_MAX_ATTEMPTS).
        "awaiting_approval", "rejected", "revision_requested",
    ] = Field(
        default="pending",
        description="Current task state. The Orchestrator mutates this field during execution.",
    )
    requires_iteration: bool = Field(
        default=False,
        description=(
            "Routes this step to the autonomous ReAct execution cell (continuous "
            "run-read-edit-rerun loop over a live terminal) instead of the one-shot "
            "coder path. Set for multi-step debugging / test-fix / iterate-until-green "
            "work; leave False for trivial single-shot edits and commands. Additive and "
            "backward-compatible: older plans without the field default to the one-shot path."
        ),
    )
    depends_on: Optional[List[int]] = Field(
        default=None,
        description=(
            "Optional list of step_numbers this step depends on. When present, "
            "ValidateWBSDependenciesTool enforces that the resulting graph is acyclic "
            "and that every referenced step_number exists in the same plan. Additive "
            "and backward-compatible: older plans without this field deserialize as None."
        ),
    )
    agent_notes: Optional[str] = Field(
        default=None,
        description=(
            "A directive FOR THE CODER ONLY (e.g. a tool-usage constraint a post-"
            "generation annotator appends, such as the polyglot-file patch-tool "
            "requirement) — never rendered on the human-facing checklist, never "
            "folded into a semantic-cache key or a retrieval query. Additive and "
            "backward-compatible: older plans without this field deserialize as None."
        ),
    )

    @model_validator(mode="before")
    @classmethod
    def _migrate_legacy_target_role(cls, data: Any) -> Any:
        """Map legacy 5-value role names to new 8-value canonical names.

        Runs BEFORE Pydantic field validation so the Literal narrows cleanly to
        the post-migration set. Idempotent: already-new values pass through
        unchanged. Tolerates non-dict input (Pydantic internal construction).
        """
        if isinstance(data, dict):
            legacy = data.get("target_role")
            if isinstance(legacy, str) and legacy in _LEGACY_TO_NEW_ROLE:
                data["target_role"] = _LEGACY_TO_NEW_ROLE[legacy]
            # Coerce an out-of-vocabulary role to the safe default instead of
            # raising a Literal ValidationError.
            role = data.get("target_role")
            if isinstance(role, str) and role not in _CANONICAL_ROLES:
                data["target_role"] = _DEFAULT_ROLE
        return data


# 13.0.9 — three call sites (engine.py's RELAY selector, guardrails.py's stall
# guard, guardrails.py's advance predicate) all select WBS steps by status, and
# guardrails.py's route_after_validation documents their agreement as an
# invariant: "Uses the SAME status == 'pending' predicate route_to_coders
# selects on, so routing and dispatch never disagree." Widening the status
# vocabulary (revision_requested, awaiting_approval, rejected) breaks that
# invariant in three DIFFERENT ways unless all three move together — a
# revision never re-dispatched, a turn ending early instead of revising, or a
# non-advancing step never tripping the stall guard. One shared predicate pair
# instead of three copies of a status tuple is what keeps them from drifting
# apart again later.
_DISPATCHABLE_STATUSES: frozenset[str] = frozenset({"pending", "revision_requested"})
_TERMINAL_STATUSES: frozenset[str] = frozenset({"completed", "failed", "rejected"})


def is_dispatchable(step: "WBSStep", all_steps: Optional[List["WBSStep"]] = None) -> bool:
    """True when a step is eligible to be sent to a coder — it has never run
    (``pending``) or a human asked for a different attempt
    (``revision_requested``) — AND, when ``all_steps`` is supplied, every
    step named in its ``depends_on`` has itself reached ``completed``.

    ``all_steps`` is optional so this stays a drop-in for any single-argument
    caller; the two live dispatch-selection sites (``route_to_coders`` and
    ``route_after_validation``'s stall guard, per the shared-predicate
    invariant above) pass the full task list precisely so a step whose
    declared prerequisite was rejected or failed can no longer dispatch and
    run against whatever that prerequisite left on disk — or didn't.
    """
    if step.status not in _DISPATCHABLE_STATUSES:
        return False
    # getattr, not direct attribute access: several call sites (both real and
    # test-only) pass lightweight stand-ins for WBSStep that never carry this
    # field.
    depends_on = getattr(step, "depends_on", None)
    if depends_on and all_steps is not None:
        completed = {s.step_number for s in all_steps if s.status == "completed"}
        if not all(dep in completed for dep in depends_on):
            return False
    return True


def is_terminal(step: "WBSStep") -> bool:
    """True when a step has reached an end state the RELAY loop will never
    revisit: applied (``completed``), a system-side fault (``failed``), or a
    human declined it outright (``rejected``). ``awaiting_approval`` and
    ``revision_requested`` are deliberately NOT terminal — the former is mid-
    decision, the latter is dispatchable again."""
    return step.status in _TERMINAL_STATUSES


class MissionSpecification(BaseModel):
    """
    THE MACRO-CONTRACT (Spec-Driven Development).
    Forces the PlannerAgent to define the complete architecture before writing a single line of code.
    """

    outcome: str = Field(
        description="The final expected result and the value this mission delivers."
    )
    scope: List[str] = Field(
        description="Strict definition of what is IN and OUT of scope. Which files to touch and which NOT to."
    )
    constraints: List[str] = Field(
        description="Technical limitations (e.g. no external libraries, O(n) complexity, project conventions)."
    )
    decisions: List[str] = Field(
        description="Design or architecture decisions adopted to solve this particular problem. "
        "Convention: when a technology stack was chosen or confirmed for this mission, it is "
        "recorded as the first entry (see agents/planner.py::_STACK_GUIDANCE_DIRECTIVE) — "
        "to_context_block() below relies on that ordering to survive truncation."
    )
    tasks: List[WBSStep] = Field(
        description="Work Breakdown Structure (WBS). The strict, sequential list of steps to execute."
    )
    checks: List[str] = Field(
        description="Technical acceptance criteria. How will the Testing micro-swarm know the task succeeded?"
    )
    # Optional; defaults preserve backward compatibility with plans authored before
    # these DDD/SDD/TDD fields existed.
    ubiquitous_language: Dict[str, str] = Field(
        default_factory=dict,
        description="DDD: domain terms → definitions extracted from the Socratic session.",
    )
    deep_modules_sdd: Optional[str] = Field(
        default=None,
        description="Architectural SDD for core modules identified during ideation.",
    )
    tdd_criteria: List[str] = Field(
        default_factory=list,
        description="TDD acceptance criteria generated from the Socratic Q&A session.",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_hallucinated_str_lists(cls, data: Any) -> Any:
        """Coerce dict/scalar hallucinations in the ``List[str]`` fields.

        The contract (immutable per SCHEMA_EVOLUTION.MD) is unchanged: these fields
        remain ``List[str]``. This before-validator only normalises malformed LLM
        output (objects where strings belong) so a structurally-valid plan no longer
        burns a retry. Mirrors WBSStep._migrate_legacy_target_role. Idempotent and
        tolerant of non-dict input (Pydantic internal construction).
        """
        if isinstance(data, dict):
            for _field in ("scope", "constraints", "decisions", "checks", "tdd_criteria"):
                if _field in data and data[_field] is not None:
                    data[_field] = _coerce_str_list(data[_field])
        return data

    def to_context_block(self, max_entries: int = 6, max_chars: int = 600) -> str:
        """Bounded projection of this mission's ``decisions``/``constraints`` for a code
        generator's prompt (both `agents/coder.py` and `brain/agentic_cell.py` consume this).

        Neither generator reads `mission_spec` for anything beyond step lookup/status today,
        so a stack choice recorded in `decisions` (see that field's docstring — the stack
        entry is convention-first) never reached the code it was meant to constrain, and a
        multi-step build could drift per step. This method is the single, bounded seam that
        fixes that without widening the wire contract: it emits data, not a new field.

        `decisions` are emitted before `constraints`, and both are truncated (never silently
        dropped) once `max_chars` is exhausted — the stack decision, always the first `decisions`
        entry by convention, is therefore the last thing to be cut under pressure. Returns ""
        when there is nothing to say, so a caller can splice it in unconditionally.
        """
        lines: List[str] = []
        for label, items in (("Decision", self.decisions), ("Constraint", self.constraints)):
            for item in items[:max_entries]:
                lines.append(f"- {label}: {item}")

        if not lines:
            return ""

        body = "\n".join(lines)
        if len(body) > max_chars:
            body = body[:max_chars].rstrip() + " …"
        return "MISSION CONTEXT (binding — decisions already made for this build):\n" + body


class ContextMeter(BaseModel):
    """Telemetry for the 3D routing engine (Local vs Cloud)."""

    semantic_similarity: float = Field(
        ge=0.0, le=1.0, description="Semantic similarity score (LanceDB)."
    )
    graph_coverage: float = Field(
        ge=0.0, le=1.0, description="Dependency-graph coverage (NetworkX)."
    )
    recency_score: float = Field(
        ge=0.0, le=1.0, description="Weight derived from recently modified files."
    )
    css_total: float = Field(
        ge=0.0,
        le=100.0,
        description="Context Sufficiency Score (global context metric).",
    )
    task_complexity_index: float = Field(
        ge=0.0, le=100.0, description="Computed complexity index of the task."
    )
    routing_decision: str = Field(
        pattern="^(LOCAL_SMALL|LOCAL_MEDIUM|LOCAL_BIG|CLOUD)$",
        description="The router's decision (core.memory.context_auditor.derive_routing_decision).",
    )
    is_red_alert: bool = Field(
        description="True when the CSS is critically low (<40%)."
    )


class LLMProfile(BaseModel):
    """Signature of the model currently in use."""

    model_name: str
    parameters_b: float
    context_window: int
    quantization: str


class TokenCounter(BaseModel):
    """Usage and cost audit."""

    local: int = 0
    cloud: int = 0
    total_cost_usd: float = 0.0


class VFSFile(BaseModel):
    """Representa un archivo en memoria con control de concurrencia (Virtual File System).

    Phase 2.2.D: content replaced by blob_hash — file text lives in ContentAddressableStorage
    (core/blob_storage.py). The LangGraph checkpoint only carries the tiny hash, keeping
    serialised state O(hash_length) regardless of file size.
    """

    blob_hash: str = Field(
        ...,
        description="blake2b hex digest of file content stored in ContentAddressableStorage.",
    )
    document_version_id: str = Field(
        ...,
        description="Timestamp o Hash MD5 para OCC (Optimistic Concurrency Control).",
    )
    is_dirty: bool = Field(
        default=False,
        description="True when the AI modified it and the change is not yet synced to the user's IDE.",
    )


class ManualAttachment(BaseModel):
    """Multimodal context manually attached by the user (image or document)."""

    type: Literal["image", "document"]
    data: Optional[str] = Field(
        default=None,
        max_length=10_485_760,  # 10 MB ceiling on base64 payload to prevent OOM
        description="Base64-encoded bytes (images only).",
    )
    content: Optional[str] = Field(default=None, description="Plain-text document body.")
    mime: Optional[str] = Field(default=None, description="MIME type, e.g. 'image/png'.")
    name: Optional[str] = Field(default=None, description="Attached file name.")


# =====================================================================
# 2. ESTADO DEL GRAFO (AIlienant Context) (LangGraph TypedDict)
# =====================================================================


def _merge_generated_code(
    left: Dict[str, "VFSFile"], right: Dict[str, "VFSFile"]
) -> Dict[str, "VFSFile"]:
    """Reducer for parallel CoderAgent output buffers. Keeps the entry with the
    lexicographically later document_version_id so the most recent generated edit
    survives multi-agent fan-out collisions."""
    merged = dict(left)
    for path, file in right.items():
        if path not in merged or file.document_version_id > merged[path].document_version_id:
            merged[path] = file
    return merged


def _merge_vfs(left: Dict[str, "VFSFile"], right: Dict[str, "VFSFile"]) -> Dict[str, "VFSFile"]:
    """Reducer for concurrent CoderAgent VFS writes. Keeps the file with the
    lexicographically later document_version_id (timestamp/hash), preventing
    a slower parallel branch from overwriting a more recent edit."""
    merged = dict(left)
    for path, file in right.items():
        if path not in merged or file.document_version_id > merged[path].document_version_id:
            merged[path] = file
    return merged


def _merge_messages(
    existing: List[Dict[str, str]],
    update: List[Dict[str, str]],
) -> List[Dict[str, str]]:
    """Default: append (operator.add semantics).
    If update[0] has __replace__=True, replace entire history with the rest of update.
    """
    if update and update[0].get("__replace__"):
        return [m for m in update if not m.get("__replace__")]
    return existing + update


def _resolve_step_id(left: Optional[int], right: Optional[int]) -> Optional[int]:
    """Reducer for current_step_id under SWARM fan-out. The MapReduce router sends one
    CoderAgent per WBS task in the same super-step, and each writes its own step_number
    back; with no reducer LangGraph cannot merge the concurrent scalar writes and raises
    INVALID_CONCURRENT_GRAPH_UPDATE. Keep the highest step_number so the post-swarm
    pointer advances monotonically toward completion. None is the 'no pending step'
    sentinel (e.g. the orchestrator's all-complete write) and is treated as 'no opinion',
    so it never clobbers a concurrent real step."""
    if left is None:
        return right
    if right is None:
        return left
    return max(left, right)


def _resolve_target_role(left: Optional[str], right: Optional[str]) -> Optional[str]:
    """Reducer for target_role under SWARM fan-out. The MapReduce router sends one
    CoderAgent per WBS task in the same super-step, and each writes back the role of
    the step it handled; with no reducer LangGraph cannot merge the concurrent scalar
    writes and raises INVALID_CONCURRENT_GRAPH_UPDATE. Keep the latest non-None write
    — None is the 'no opinion' sentinel (e.g. the orchestrator's all-complete reset)
    and never clobbers a concurrent real role."""
    return right if right is not None else left


def _merge_todos(
    left: Optional[List[Dict[str, Any]]], right: Optional[List[Dict[str, Any]]]
) -> List[Dict[str, Any]]:
    """Reducer for an agent's TODO list — replace-semantics, swarm-safe.

    A write rewrites the whole list (the tool always emits the full set), so the latest
    write wins. The distinction that matters: None means 'no opinion this turn' and keeps
    the prior list, while an explicit empty list [] means 'I finished — clear my panel'.
    Testing truthiness (``right if right else left``) would make that clear impossible —
    an empty list would be read as 'no opinion' and the completed TODOs would never go
    away. So branch on ``is not None``, never on emptiness."""
    if right is not None:
        return right
    return left or []


class AIlienantGraphState(TypedDict):
    """
    The shared brain of the LangGraph flow.
    Strictly defines the memory and variables nodes may read or mutate.
    """

    # --- Mission Identity ---
    task_id: str
    user_input: str
    # Wall-clock epoch (time.time()) set once by core/task_service.py's
    # session-start resolver on the first turn of a session, then carried
    # forward unchanged on every later turn while L1 stays warm. No graph
    # node ever writes this — read-only downstream, used to derive session
    # duration for context-utilization telemetry. Absent/None on a checkpoint
    # written before this field existed.
    session_start_time: Optional[float]

    # --- Workspace Identity & Manual Context (Phase 1.1.0 / 1.1.0.4) ---
    project_id: Optional[str]              # SHA-256 of the VS Code workspace root path
    workspace_root: Optional[str]          # Absolute path of the VS Code workspace; set from _workspace_registry
    explicit_mentions: List[str]           # @-referenced file paths → forced full-file read
    attachments: List[ManualAttachment]    # user-attached images / documents

    # --- Message Memory ---
    # O(N) cumulative history backing the conversational channel.
    messages: Annotated[List[Dict[str, str]], _merge_messages]

    # --- Context & Telemetry ---
    context_metrics: ContextMeter
    active_llm_profile: LLMProfile
    token_usage: TokenCounter

    # --- Flow Control (Prompt Swapping) ---
    is_manual_override: bool
    # Reducer-guarded: SWARM fan-out makes multiple CoderAgents write their own
    # step's role in one super-step; _resolve_target_role merges them (see docstring).
    target_role: Annotated[
        Optional[str], _resolve_target_role
    ]  # Replaces 'target_agent'. The active CoderAgent role.
    # Reducer-guarded: SWARM fan-out makes multiple CoderAgents write their own
    # step_number in one super-step; _resolve_step_id merges them (see its docstring).
    current_step_id: Annotated[
        Optional[int], _resolve_step_id
    ]  # Pointer to the WBS task currently executing (step_number).

    # --- Human-in-the-Loop & Planner Mode (Phase 1.4 / 2.21) ---
    planner_mode_active: bool       # True when user toggled Planner-only mode via WS event
    hitl_pending: bool              # True while the graph is awaiting human approval
    hitl_response: Optional[str]   # "approved" | "rejected" + optional comment from HITL response
    shared_understanding_reached: bool  # Phase 2.21: True once analyst confirms Socratic dialogue complete
    # ideation_synthesized: set by synthesis_node once the Socratic dialogue is distilled
    #   into a planner brief; route_after_ideation reads it to hand the turn to
    #   planner_agent instead of dead-ending at END. Scalar overwrite (written once per
    #   synthesis turn). MUST stay declared here — LangGraph silently drops any state key
    #   a node returns that isn't a channel on this TypedDict (see assert_declared_channels
    #   below), which is exactly how this handoff went dark before it was declared.
    ideation_synthesized: bool
    # ideation_glossary: ubiquitous language ({term: definition}) settled during the
    #   Socratic dialogue, folded into the planner's context. Scalar overwrite.
    ideation_glossary: Dict[str, str]
    # grill_round_count: how many analyst_grill rounds have run this ideation session.
    #   Each round is now its own graph super-step (a self-loop edge on analyst_grill,
    #   brain/ideation.py), with the human's answer for that round resolved via native
    #   interrupt()/resume rather than a fresh top-level invocation — so a round cannot
    #   track its own count in a local Python variable the way the old
    #   one-question-per-top-level-turn design implicitly did via separate invocations.
    #   Scalar overwrite; used as the _GRILL_MAX_ROUNDS circuit breaker.
    grill_round_count: int
    # pending_grill_batch: the current round's question batch (already-serialized
    #   dicts, questions_to_pending_dicts' output), committed to state by
    #   analyst_grill's generate phase BEFORE the self-loop revisits the node for
    #   its ask phase. Required by the same invariant pending_exec_command/
    #   pending_tool_call/pending_hitl_request enforce elsewhere (brain/agentic_cell.py):
    #   interrupt() must be the node's FIRST action, since LangGraph replays
    #   everything before it on every resume — a batch generated in the SAME
    #   invocation that calls interrupt() would be silently regenerated
    #   (non-deterministically) on replay, misaligning the ids the operator
    #   actually answered. None once the ask phase resolves and clears it.
    pending_grill_batch: Optional[List[Dict[str, Any]]]
    # pending_brief: the distilled planner brief awaiting the operator's review,
    #   committed by synthesis_node's draft phase before the self-loop revisits the
    #   node for its review phase — the same defer-then-interrupt-first invariant
    #   pending_grill_batch enforces above, and for a costlier reason: the draft is
    #   a MODEL_BIG call, so a brief generated in the same invocation that calls
    #   interrupt() would be regenerated on every replay, silently charging for a
    #   brief the operator never saw and swapping out the text under review.
    #   Carries the composed brief ("composed" — rendered verbatim for review, since
    #   _compose_planner_brief already emits the settled constraints and scope as
    #   their own labelled blocks, which is what makes an OMITTED one noticeable)
    #   plus the glossary, which becomes ideation_glossary only once accepted.
    #   None once the review resolves. Scalar overwrite.
    pending_brief: Optional[Dict[str, Any]]
    # brief_revision_note: the operator's steering instruction when they send a brief
    #   back to be rewritten. Consumed by the next draft phase (appended to the
    #   distillation's user payload, never to its system prompt) and cleared there.
    #   Scalar overwrite.
    brief_revision_note: Optional[str]
    # Agentic-cell exec-approval deferral: the command awaiting human approval, set when
    # the cell defers a HITL-gated run_terminal so the interrupt happens in a clean,
    # side-effect-free re-entry rather than mid-iteration.
    pending_exec_command: Optional[str]
    # Agentic-cell registry-fallback deferral (DEBT-129): a HITL-tier tool name outside
    # the 3 CELL_TOOLS primitives, awaiting human approval before it executes. Mirrors
    # pending_exec_command's defer-then-interrupt-first pattern for an arbitrary
    # registry-resolved tool call rather than the single hardcoded run_terminal command.
    # Shape: {"name": str, "args": dict} — args pre-clamped by the writer, never raw.
    pending_tool_call: Optional[Dict[str, Any]]

    # --- Immutable Planning (SDD) ---
    # The whole plan lives inside this single object so the two halves can never drift apart.
    mission_spec: Optional[MissionSpecification]

    # --- Virtual File System (VFS) ---
    # Single source of truth for the code.
    read_files_state: Dict[str, VFSFile]
    vfs_buffer: Annotated[Dict[str, VFSFile], _merge_vfs]

    # --- MoE Routing ---
    # Shortcuts so orchestration nodes can read TCI/CSS without walking context_metrics.
    tci: float          # Task Complexity Index  0–100
    css: float          # Context Sufficiency Score  0–100
    # MapReduce fan-out payload: PlannerAgent writes it, route_to_coders reads it.
    parallel_tasks: List[WBSStep]

    # --- Routing & Hardware (Phase 2.1) ---
    # True when at least one attachment is type="image" → forces CLOUD via Vision Bypass.
    has_images: bool
    # Set by core.memory.context_auditor.hardware_reroute() when a LOCAL
    # decision is downgraded/rerouted (insufficient VRAM, predicted context
    # overflow); None otherwise.
    routing_warning: Optional[str]
    # Populated by orchestrator node on first invocation; cached in checkpoint state.
    hardware_profile: Optional[HardwareProfile]
    # Active routing decision written by the orchestrator; read by route_to_coders.
    provider: str
    # Parallel CoderAgent output buffer; _merge_generated_code prevents fan-out collisions.
    generated_code: Annotated[Dict[str, VFSFile], _merge_generated_code]

    # --- Resilience & Diagnostics ---
    errors: Annotated[List[str], operator.add]
    retry_count: int
    security_flags: Annotated[List[str], operator.add]
    terminal_output: str
    # Phase 3.4.2: Pre-Dream Reflection — compact summary of last session written by
    # session_delta_aggregator_node before each planner turn. Empty string on first turn.
    session_delta: str
    # Phase 4.1.1: Researcher Skeleton Map — written by run_researcher_node before planner in
    # FULL_SWARM mode. None when the run skips the Researcher (SEQUENTIAL / MICRO_SWARM).
    researcher_skeleton: Optional[str]
    # Phase 4.1.2: PlannerAgent retry telemetry — number of ValidationError retries the
    # planner consumed on the current invocation (0 = first-shot success). Bounded by
    # MAX_PLANNER_RETRIES (= 2). Overwrite semantics; not a reducer.
    planner_retry_count: int

    # Phase 4.2 — Deterministic Validators (blueprint §4.2 + §4.1 thresholds).
    # All additive, overwrite semantics (no reducer). The gate nodes write them;
    # the Give-Up Gate logic (inlined in style_gate_node) reads syntax_gate_status
    # + consecutive_style_failures to decide whether to latch style_bypass_active.
    # Engine wiring lives in Phase 4.3.
    venv_interpreter_path: Optional[str]
    relaxed_typing_mode: bool
    style_bypass_active: bool
    consecutive_style_failures: int
    syntax_gate_status: Literal["pass", "fail", "pending"]
    # ──────────────────────────────────────────────────────────────────────
    # Phase 4.2 TRANSITIONAL — code_under_validation
    # ──────────────────────────────────────────────────────────────────────
    # This field exists ONLY so Phase 4.2 unit tests can inject code into the
    # gate nodes without coupling to vfs_buffer / blob_storage. It DUPLICATES
    # content that already lives in vfs_buffer (Dict[str, VFSFile]) and
    # pending_patches (Dict[str, str] diffs). Persisting it inflates the
    # SQLite WAL + LanceDB checkpoint by O(N) per patch — STATE BLOAT.
    #
    # TODO(phase-4.3): when engine wiring lands, replace gate-node reads of
    # this field with resolution from vfs_buffer (via core/blob_storage) or
    # pending_patches (in-memory diff apply). Then REMOVE this field from the
    # TypedDict and update the tests to point at a RunnableConfig.metadata
    # channel or equivalent ephemeral surface. Tracked in
    # docs/PROJECT_MANIFEST.md Tech Debt section.
    # ──────────────────────────────────────────────────────────────────────
    code_under_validation: Optional[str]

    # --- Guardrail State (Phase 2.1.14) ---
    guardrail_failed: bool              # True if validate_output detected a schema violation
    validation_feedback: Optional[str]  # Corrective message prepended to CoderAgent on retry

    # --- Shallow State / Patch Queue (Phase 2.2.D) ---
    # CoderAgent (Phase 4) writes unified diffs here; apply_patch_node consumes them.
    # operator.or_ merges dicts by preferring the right-hand (latest) value per key.
    pending_patches: Annotated[Dict[str, str], operator.or_]  # filepath → unified diff
    # Phase 7.9.B.18 — write pipeline: the coder also emits the full new content and
    # a pre-edit hash per changed file so the approved patch can be actuated via the
    # VS Code applyEdit bridge (content) with a stale-file guard (hash).
    pending_contents: Annotated[Dict[str, str], operator.or_]   # filepath → full new content
    pending_base_hash: Annotated[Dict[str, str], operator.or_]  # filepath → sha256(pre-edit, EOL-normalized)

    # --- Incremental Apply Gate (13.0.9) ---
    # pending_patches/pending_contents/pending_base_hash above use operator.or_ and
    # can NEVER be cleared — returning {} merges to a no-op — so the apply-gate
    # prepare node cannot "take the pending set" for one step; it must be told
    # which paths belong to THIS step. Keys are str(step_number): the checkpoint
    # serializer round-trips JSON object keys as strings, so an int-keyed dict is
    # a latent mismatch after a cold restore.
    pending_step_files: Annotated[Dict[str, List[str]], operator.or_]     # str(step_number) → [filepath, ...]
    pending_step_command: Annotated[Dict[str, str], operator.or_]        # str(step_number) → raw command
    # The prepared-but-not-yet-decided approval envelope for the step apply_commit
    # is about to interrupt on. Scalar overwrite (one step is ever "in flight" at
    # a time under RELAY). Carries diffs, not file bodies — apply_commit re-reads
    # the full new content from pending_contents, which is already checkpointed
    # and stable across the pause, keeping the interrupt() payload O(Δ). MUST stay
    # plain dicts (never Pydantic instances): this value is serialized into the
    # checkpoint's pending writes as the interrupt() argument.
    pending_apply: Optional[Dict[str, Any]]
    # A "request changes" verdict's feedback, scoped to the step it was given
    # for — the coder asserts step_number == current_step_id before folding it
    # into its regeneration prompt, so a stale comment from an earlier step can
    # never leak into a later one's generation.
    apply_feedback: Optional[Dict[str, Any]]
    # Revision attempts per step, bounding APPLY_REJECT_MAX_ATTEMPTS so an operator
    # repeatedly requesting changes can't spin a step to the recursion limit.
    apply_attempts: Annotated[Dict[str, int], operator.or_]  # str(step_number) → count
    # Steps whose apply_commit has already resolved (approved, rejected, or
    # denied) — the idempotency check a resumed apply_commit consults first, so
    # a double-delivered resume can never re-apply the same step's write twice.
    applied_step_ids: Annotated[List[int], operator.add]
    # Turn-scoped, human-readable ledger of what happened to each step's apply —
    # sourced for the honest turn-end summary in place of predicting a gate
    # outcome before any approval happened.
    applied_files_log: Annotated[List[Dict[str, Any]], operator.add]
    # Mirrors TaskPayload.auto_accept_low_risk onto graph state (same DEBT-079
    # rationale as enable_native_thinking above) — the apply gate's prepare node
    # needs it and only has state/config, never the original TaskPayload. Scalar,
    # no reducer: set once at turn start, read-only for the rest of the turn.
    auto_accept_low_risk: bool
    # Verdict per MissionSpecification.checks entry ({check, command, status,
    # detail?}, status one of passed/failed/unverified) — written once by
    # brain/checks_gate.py::run_checks_node at turn end. Additive per charter
    # §10: a persisted checkpoint from before this channel existed simply
    # rehydrates it as empty, never breaking.
    check_results: Annotated[List[Dict[str, Any]], operator.add]

    # --- FinOps Budget Gate (Phase 2.18) ---
    # operator.add reducer required: parallel Send() fan-out means multiple CoderAgent
    # branches write a cost delta simultaneously; reducer sums them safely.
    # Phase 4 CoderAgent returns {"current_cost_usd": delta_usd} per invocation.
    current_cost_usd: Annotated[float, operator.add]
    # Fixed ceiling injected once at graph invocation from env (AILIENANT_MAX_BUDGET_USD).
    # No reducer: this value is never aggregated, only read by the finops_gate node.
    max_budget_usd: float

    # Heuristic cost estimate for the committed mission plan, produced by the Planner's
    # pre-commit BudgetEstimatorTool. Scalar overwrite — no reducer. None until the
    # first clean plan draft clears both Pydantic and WBS validation.
    budget_estimate: Optional[Dict[str, Any]]

    # --- Contract Guard (Phase 2.23) ---
    # Render signal emitted by ContractGuardNode when a drift trigger fires; consumed
    # by the VS Code extension to render a persistent banner. Cleared by the extension
    # on ack. Scalar overwrite — no reducer.
    ui_payload: Optional[Dict[str, object]]
    # Anchor snapshot of the state at the last contract emission. Read-only for all
    # nodes except ContractGuardNode. Holds {"tci": float, "target_role": Optional[str],
    # "turn": int}. None until the first emission. Scalar overwrite — no reducer.
    contract_anchor: Optional[Dict[str, object]]

    # --- Resource Broker (Phase 2.27) ---
    # Blocking-modal render signal emitted by ResourceBroker on cross-session VRAM
    # contention. Distinct from `ui_payload` (Phase 2.23 — non-blocking banner) so
    # the two cannot collide in the same turn. Cleared by the extension once the
    # user picks a resolution. Scalar overwrite — no reducer.
    ui_interrupt: Optional[Dict[str, object]]
    # Telemetry snapshot at the moment of contention: conflicting model, queue
    # position, recommendation. Owned by ResourceBroker; read-only elsewhere.
    contention_status: Optional[Dict[str, object]]
    # User's response to the most recent contention prompt: "WAIT" | "SWITCH_TO_CLOUD"
    # | "CANCEL". Set by the broker from the HitL reply; consumed within the same
    # node invocation. Scalar overwrite — no reducer.
    user_resource_resolution: Optional[Literal["WAIT", "SWITCH_TO_CLOUD", "CANCEL"]]

    # --- Effort Budget ---
    # Written once at turn start; controls verification depth on the main graph
    # (lint/LSP gate, self-heal attempt ceiling, whether the plan's own
    # acceptance checks run — see brain/retry_policy.py and
    # brain/checks_gate.py). Replaces the old SEQUENTIAL/MICRO_SWARM/FULL_SWARM
    # execution_mode selector, which named a topology no routing decision in
    # brain/engine.py ever actually consulted — a different, unrelated axis
    # from TaskPayload.execution_mode (the AUTO/ASK/PLAN permission mode,
    # unaffected by this rename).
    effort_level: Literal["light", "balanced", "deep"]

    # --- Phase 4.3 stage-2 — MICRO_SWARM / FULL_SWARM channels ---
    # active_role: written by Orchestrator (1:1 copy of WBSStep.target_role for the
    #   active step); read by CoderAgent prompt builder and tool-filter.
    # error_streak: written by SyntaxGate/StyleGate on fail; reset on step transition;
    #   read by Circuit Breaker (escalates at CIRCUIT_BREAKER_THRESHOLD = 3).
    # style_gate_status: split from consecutive_style_failures so MICRO_SWARM router
    #   can distinguish "broken code" from "ugly code" without re-deriving from counts.
    # circuit_breaker_tripped: latched True once tripped; read by route_to_coders.
    # cloud_surgeon_invocations: operator.add — bounded to MAX_CLOUD_SURGEON=1 by Circuit Breaker.
    active_role: Optional[Literal[
        "core_dev", "architect_refactor", "devops_infra", "secops",
        "qa_tester", "doc_manager", "vcs_manager", "data_ml_engineer",
    ]]
    error_streak: int
    style_gate_status: Literal["pass", "fail", "pending"]
    circuit_breaker_tripped: bool
    cloud_surgeon_invocations: Annotated[int, operator.add]

    # --- Phase 4.4 — Lifecycle & PID Manager channels ---
    # workspace_pid: VS Code window PID sent by the extension on client_workspace_init.
    # workspace_active: latched False by lifecycle_manager.shutdown_workspace(pid).
    workspace_pid: Optional[int]
    workspace_active: bool

    # --- Phase 5.1 — Permission Engine & Cognitive Quarantine channels ---
    # session_permission_mode: per-mission HITL policy. Canonical 7-mode vocabulary
    # (FULL_AUTO / STANDARD / CAUTIOUS / ASK_EXECUTE / ASK_ALL / READ_ONLY / PLAN_ONLY)
    # plus the deprecated legacy aliases (DEFAULT / PLAN / AUTO) kept for checkpoint
    # back-compat. Stored UPPERCASE; SessionPermissionMode.value is lowercase.
    # boundary_id: per-turn uuid4().hex used by the Cognitive Quarantine axiom.
    # tool_registry_active: names of tools surfaced to the model this turn (Tool RAG).
    # permission_audit_log: append-only ledger of every permission decision.
    # pending_hitl_request: structured payload awaiting WebView user response.
    # background_tasks: registry of long-running asyncio tasks keyed by task_id.
    # mcp_server_endpoint: active MCP ClientSession URI (None = local-only).
    # rbwe_violations: append-only list of "tool::target" RBWE rejections.
    session_permission_mode: Literal[
        "FULL_AUTO", "STANDARD", "CAUTIOUS", "ASK_EXECUTE", "ASK_ALL", "READ_ONLY", "PLAN_ONLY",
        "DEFAULT", "PLAN", "AUTO",
    ]
    boundary_id: Optional[str]
    tool_registry_active: List[str]
    permission_audit_log: Annotated[List[Dict[str, Any]], operator.add]
    pending_hitl_request: Optional[Dict[str, Any]]
    background_tasks: Dict[str, Dict[str, Any]]
    mcp_server_endpoint: Optional[str]
    rbwe_violations: Annotated[List[str], operator.add]

    # tool_dispatch_trace: append-only record of tool calls a cognitive node
    # actually executed through the runtime dispatch loop (name + args per entry).
    # Lets the graph and tests observe that a registered tool was invoked end-to-end.
    tool_dispatch_trace: Annotated[List[Dict[str, Any]], operator.add]

    # --- Phase 6 — Operational Safety Layer channels (PHASE_6_BLUEPRINT §1) ---
    # All scalar overwrite (no reducer) with safe defaults — Phase 5.7 checkpoints
    # deserialise unchanged. Landed in Phase 6.3 (OOM Cascade needs
    # oom_fallback_active); the rest front-load the 6.4/6.5 Supervisor + DLQ work.
    #
    # accumulated_session_cost: USD cost across the WHOLE WebSocket session
    #   (many tasks), written by core/supervisor.py from token_ledger.snapshot().
    # session_max_budget_usd: hard ceiling injected once at graph construction
    #   from AILIENANT_MAX_SESSION_BUDGET_USD; read by the Supervisor triggers.
    # oom_fallback_active: set True by tools/llm_gateway.py::ainvoke when it traps
    #   an OOM-class exception; read by brain/nodes/circuit_breaker.py to skip the
    #   local cascade; reset to False once the fallback turn is acknowledged.
    # sandbox_tier_active: mirror of core.sandbox.ACTIVE_TIER injected at graph
    #   start so nodes can reason about posture without importing the global.
    # hitl_audit_chain_head: blake2b chain_hash of the last resolved
    #   hitl_audit_log row; the Supervisor verifies it against the DB head.
    # dead_letter_episode_id: episode_id of a resumed DLQ turn; None for fresh
    #   tasks; rendered by the AnalystAgent post-mortem.
    accumulated_session_cost: float
    session_max_budget_usd: float
    oom_fallback_active: bool
    sandbox_tier_active: Literal["DOCKER", "WASM", "NATIVE_HITL"]
    hitl_audit_chain_head: Optional[str]
    dead_letter_episode_id: Optional[str]

    # --- Phase 7.11.3 (ADR-706 §4.5b) — Abort Controller Mesh savepoint marker ---
    # Populated by the orchestrator (core/task_service.py) inside the
    # `except asyncio.CancelledError` block when the user clicks Stop. The value
    # is "user_abort" per the blueprint; future fault classes can extend the
    # taxonomy (e.g., "budget_kill" / "timeout"). Cold-serializable string — the
    # next HybridCheckpointer.promote() carries it into SQLite/LanceDB without
    # any schema migration. UI consumers read it on rehydrate to render a
    # "Stopped by user" indicator without breaking graph topology. None on
    # normal completion. Scalar overwrite, no reducer.
    termination_reason: Optional[str]

    # --- Self-Healing Reflexion Loop channels ---
    # All additive, scalar overwrite, safe defaults — older checkpoints rehydrate
    # unchanged. reflexion_guard sets healing_required + the diagnostic fields when
    # it traps a node exception; the ErrorCorrectionAgent reads them, proposes a
    # HITL-gated fix, and clears healing_required. correction_attempts is the in-turn
    # budget bound; failure_signature is the normalized cross-turn breaker key.
    healing_required: bool
    correction_attempts: int
    last_error_trace: Optional[str]
    failed_node: Optional[str]
    failure_signature: Optional[str]
    # 13.0.9 — set ONLY alongside a healing_required=True signal that originated
    # from a run_command failure (brain/apply_gate.py::_commit_command, which
    # also sets failed_node="apply_commit" in the SAME return dict). Consumers
    # must gate on failed_node=="apply_commit" before reading this — like every
    # other field in this block it is a scalar overwrite with no cross-turn
    # staleness guard, so it is only ever trustworthy together with the fresh
    # failed_node value written by the exact same node in the exact same delta.
    # Keys: command, exit_code, stdout_tail, stderr_tail (all str/int, capped).
    last_execution_context: Optional[Dict[str, Any]]

    # --- Agentic Execution Cell (ReAct sub-loop) channels ---
    # agentic_iteration: in-turn counter for the autonomous cell; bounds the loop
    #   against AGENTIC_CELL_MAX_ITERATIONS so a non-converging task concedes
    #   gracefully instead of spinning. Scalar overwrite; the cell owns it.
    # agentic_trajectory: append-only ledger of one record per ReAct iteration
    #   (the structured verdict, applied edits, and any OCC-collision diagnostic).
    #   It rides the LangGraph checkpoint, so each loop-back leaves a Rewind-able
    #   record. operator.add reducer keeps parallel/resumed writes additive.
    # cell_tool_query: the discovery query the model passed to `tool_search` on
    #   the previous iteration, replayed by the next one so the tool's "name it
    #   next turn and its schema is injected" instruction resolves to the exact
    #   tools it listed. Scalar overwrite (no reducer): written on every cell
    #   return, cleared once consumed, so a stale query cannot keep re-selecting.
    agentic_iteration: int
    agentic_trajectory: Annotated[List[Dict[str, Any]], operator.add]
    cell_tool_query: Optional[str]

    # --- Universal agent TODO list channel ---
    # A per-agent task scratchpad written by the universal `todo_write` tool. Each item is
    # {content: str, status: "pending"|"in_progress"|"completed", active_form: str}. Replace
    # semantics via _merge_todos: a write rewrites the full list (latest wins); None keeps the
    # prior list; [] explicitly clears it. Additive and safe-defaulted — older checkpoints
    # rehydrate unchanged (readers use `state.get("agent_todos") or []`).
    agent_todos: Annotated[List[Dict[str, Any]], _merge_todos]

    # --- Dynamic Subagent Dispatch channels ---
    # All additive & default-safe so a pre-dispatch checkpoint deserializes
    # unchanged: the scalar channels are absent-until-written (readers use
    # state.get → None/0), and the trace ships with an operator.add reducer from
    # the outset so concurrent Send() branches append without a merge conflict.
    # The plan/result channels hold model_dump() dicts (not the Pydantic models
    # themselves) to keep the checkpoint plain-JSON-serializable.
    dispatch_plan: Optional[Dict[str, Any]]            # DispatchPlan.model_dump(); written by the dispatching node
    dispatch_batch_result: Optional[Dict[str, Any]]    # DispatchBatchResult.model_dump(); written by the synthesis node
    dispatch_depth: int                                # default 0; incremented before any re-dispatch
    subagent_dispatch_trace: Annotated[List[Dict[str, Any]], operator.add]  # append-only audit trail
    # Per-worker result envelopes, one per subagent Send. operator.add so the
    # concurrent fan-in writers in a super-step append without a merge conflict
    # (mirrors every other Send() fan-in channel). Never cleared mid-dispatch —
    # an operator.add channel cannot be reset, and synthesis is terminal.
    _dispatch_results: Annotated[List[Dict[str, Any]], operator.add]
    # Number of subagent waves already dispatched within one dispatch level
    # (distinct from dispatch_depth, which counts recursion). Advanced once per
    # fan-in barrier by dispatch_gate; single-writer, so no reducer. Default 0.
    dispatch_wave_count: int
    # Downstream node the dispatch subgraph returns to after synthesis. Set on
    # dispatch entry by the emitting agent (planner → "step_dispatch",
    # researcher → "planner_agent") so a single shared synthesize node routes back
    # to the correct successor. Scalar-overwrite; default None → "step_dispatch".
    dispatch_return_node: Optional[str]
    # Pattern loop-back counter (adversarial critic wave, loop-until-done
    # continuation). Distinct from dispatch_wave_count (which slices one fixed task
    # list): a round introduces a NEW task set via dispatch_advance. Default 0.
    dispatch_round_count: int
    # Result-isolation watermark: the index into _dispatch_results past which the
    # CURRENT dispatch's envelopes begin. Because _dispatch_results is operator.add
    # and cannot be cleared, synthesis digests/commits only results[consumed:], and
    # advances this to len(results) so a second dispatch in the same run never
    # re-digests or double-counts the first's envelopes. Default 0 → slice [0:].
    _dispatch_consumed: int
    # Budget reservation bookkeeping for the active dispatch. _dispatch_reserved_usd
    # is the running sum reserved against current_cost_usd (folded via that channel's
    # operator.add reducer); _dispatch_reserved_round is the highest round already
    # reserved, so a per-round reserve stays single-flight and replay-safe. Defaults 0.
    _dispatch_reserved_usd: float
    _dispatch_reserved_round: int
    # Admission verdict written by dispatch_origin, read by the admission router to
    # fan out or short-circuit to synthesis: "admit" | "denied" | "budget_exhausted".
    _dispatch_admission: Optional[str]

    # --- Reasoning-mode task config (mirrors TaskPayload, survives a checkpoint) ---
    # The per-turn Reasoning Mode toggle (native-thinking on/off + its token budget)
    # is otherwise threaded only via config["configurable"] (never checkpointed), so
    # a cross-restart HITL resume previously fell back to hardcoded defaults for any
    # reasoning turn produced after the resume. Mirroring it onto graph state costs
    # nothing extra to persist: HybridCheckpointer promotes once per run, not per
    # step, and these two scalars ride alongside vfs_buffer, which already carries
    # full file contents. Seeded once at task start; never mutated by a node.
    # Additive and default-safe: an older checkpoint deserializes both as absent, so
    # every reader falls back to the pre-existing literal defaults (True / 4096).
    enable_native_thinking: Optional[bool]
    thinking_budget_tokens: Optional[int]


# =====================================================================
# 3. NODE-DELTA GUARD — reject writes LangGraph would silently drop
# =====================================================================
# LangGraph's compiled StateGraph filters every node's returned dict down to the
# keys declared on this TypedDict before merging into the checkpoint
# (langgraph/graph/state.py::attach_node._get_updates: `if k in output_keys`).
# An undeclared key is dropped with NO exception and NO warning — the write simply
# never happens. That silent drop is exactly how the ideation→planner handoff went
# dark: synthesis_node returned `ideation_synthesized` for the life of the feature
# without it ever being declared here, so route_after_ideation could never see it
# and every Socratic dialogue dead-ended instead of reaching the planner.
#
# assert_declared_channels() closes that whole class of bug at the source: every
# node wrapper (brain/engine.py::_instrument_node, brain/ideation.py's subgraph
# nodes) calls it on the raw delta just before returning. It raises under pytest
# or AILIENANT_STRICT_STATE=1 so CI catches a stray key the moment it's introduced;
# in a live session it only logs, so a fault here can never crash a running turn
# (charter §5.2 — no critical path may be taken down by a diagnostic).
logger = logging.getLogger("GRAPH_STATE")

_DECLARED_CHANNELS: frozenset[str] = frozenset(AIlienantGraphState.__annotations__)


def accepts_config(fn: Callable[..., Any]) -> bool:
    """Whether ``fn`` declares a ``config`` parameter LangGraph would inject into.

    Mirrors the runtime's own admission rule (``langgraph._internal._runnable``):
    a parameter literally named ``config``, of a kind that can be passed by
    keyword. ``inspect.signature`` follows ``__wrapped__``, so a ``functools.wraps``
    decorator chain (the DLQ and reflexion guards) resolves to the real node
    underneath rather than to the wrapper.

    Lives here, beside ``assert_declared_channels``, because both node-wrapping
    helpers — the parent graph's and the ideation subgraph's — need it, and those
    two modules import each other.
    """
    try:
        param = inspect.signature(fn).parameters.get("config")
    except (TypeError, ValueError):  # builtins / C callables expose no signature
        return False
    return param is not None and param.kind in (
        inspect.Parameter.POSITIONAL_OR_KEYWORD,
        inspect.Parameter.KEYWORD_ONLY,
    )


def assert_declared_channels(node_name: str, delta: Any) -> None:
    """Reject state keys LangGraph would otherwise drop without a trace.

    Only plain-dict deltas are checked — a node returning ``None``, a ``Command``,
    or a list of ``Command``/dict (Send fan-out) is outside this check's scope and
    passes through untouched; LangGraph's own ``_get_updates`` filters those
    separately. Keys prefixed with ``__`` (e.g. the ``_merge_messages`` replace
    sentinel) are reducer-internal markers, not channel names, and are skipped.
    """
    if not isinstance(delta, dict):
        return
    unknown = sorted(
        k for k in delta if not k.startswith("__") and k not in _DECLARED_CHANNELS
    )
    if not unknown:
        return
    message = (
        f"node {node_name!r} returned undeclared state key(s) {unknown!r} — "
        "LangGraph silently drops these on write; declare them on "
        "AIlienantGraphState (brain/state.py) instead."
    )
    if os.getenv("PYTEST_CURRENT_TEST") or os.getenv("AILIENANT_STRICT_STATE") == "1":
        raise ValueError(message)
    logger.error(message)
